### ISSUE TITLE
Unable to install dingus from repo or pypi

### ISSUE THREAD

**Issue by blha303** [garybernhardt/dingus#25]
```
$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    long_description=file('README.txt').read(),
NameError: name 'file' is not defined
$ sudo pip3 install dingus
Collecting dingus
  Downloading dingus-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-90owktsy/dingus/setup.py", line 6, in <module>
        long_description=file('README.txt').read(),
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-90owktsy/dingus/
$ python3 --version
Python 3.5.1+
$ pip3 --version
pip 8.1.2 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

**Comment by blha303** [comment]
Oh, you're using Python 2. Never mind ^_^
